### ISSUE TITLE
MatlogX crashes

### ISSUE THREAD

**Issue by Enkidu70** [Magisk-Modules-Alt-Repo/MiXplorer#15]
I just tried you Magisk module. But as soon as I have installed it, [MatlogX](https://github.com/Flamingo-OS/packages_apps_MatlogX) crashes.

At this part, MatlogX should come up with choose directory dialog.

As soon as I deactivate you Magisk module, everything is fine again.

Please fix if possible. Tnx.

```
type: crash
osVersion: OnePlus/OnePlus8T_EEA/OnePlus8T:13/TKQ1.221128.002/eng.abhay.20221229.033041:user/release-keys
package: com.flamingo.matlogx:3
process: com.flamingo.matlogx

java.lang.RuntimeException: Unable to resume activity {com.flamingo.matlogx/com.flamingo.matlogx.ui.LogcatActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4810)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4843)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2310)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7951)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2181)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1816)
	at android.app.Activity.startActivityForResult(Activity.java:5517)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at o2.a$a.b(Unknown Source:0)
	at androidx.activity.ComponentActivity$b.b(Unknown Source:259)
	at androidx.activity.result.d.p(Unknown Source:25)
	at com.flamingo.matlogx.ui.LogcatActivity.onResume(Unknown Source:48)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1540)
	at android.app.Activity.performResume(Activity.java:8469)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4800)
	... 13 more

```

**Comment by Enkidu70** [comment]
Ok, guess you already has solved it due to #11.

Maybe you can give more details to the installer when it makes sense to use these options. I was not aware to get these troubles.

Tnx.

**Comment by Psk-Ita** [comment]
added some details in module read.me
