### ISSUE TITLE
Crash DocumentsUI on  Miui 13 A 12

### ISSUE THREAD

**Issue by Urzu7** [Magisk-Modules-Alt-Repo/MiXplorer#19]
`java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(Unknown Source:27)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at com.android.documentsui.ProviderExecutor.run(ProviderExecutor.java:104)
Caused by: java.lang.SecurityException: ContentService: Neither user 10056 nor current process has android.permission.CACHE_CONTENT.
	at android.os.Parcel.createExceptionOrNull(Unknown Source:7)
	at android.os.Parcel.createException(Unknown Source:0)
	at android.os.Parcel.readException(Unknown Source:11)
	at android.os.Parcel.readException(Unknown Source:10)
	at android.content.IContentService$Stub$Proxy.getCache(Unknown Source:64)
	at android.content.ContentResolver.getCache(Unknown Source:16)
	at com.android.documentsui.roots.ProvidersCache.loadRootsForAuthority(ProvidersCache.java:349)
	at com.android.documentsui.roots.ProvidersCache.getRootOneshot(ProvidersCache.java:408)
	at com.android.documentsui.roots.ProvidersCache.getRootOneshot(ProvidersCache.java:398)
	at com.android.documentsui.roots.LoadRootTask.run(LoadRootTask.java:61)
	at com.android.documentsui.roots.LoadRootTask.run(LoadRootTask.java:33)
	at com.android.documentsui.base.CheckedTask.doInBackground(CheckedTask.java:65)
	at android.os.AsyncTask$3.call(Unknown Source:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 1 more
`

**Comment by palexdev** [comment]
Happening to me too on Project Elixir Android 13
I didn't take the log but Google's DocumentUI was crashing with this module, even Firefox was crashing at one point

I installed MiX normally from XDA, everything works fine now, I honestly don't see the point of such module if it can't even work properly

**Comment by Urzu7** [comment]
The problems with Firefox and other applications were caused by the DocumentsUI not working. I have seen problems in several applications that require confirmation through DocumentsUI in order to work with the file system.

**Comment by palexdev** [comment]
What could the issue be though
I choose to keep all the apps during the installation process

**Comment by Urzu7** [comment]
I first noticed an error when installing KDE Connet and selecting a directory. After that, I realized that the problem was not KDE Connect, but DocumentsUI. In Firefox, file uploads were not working. Cleaning the cache and deleting updates did not help. The solution was found in the log, I was not the first to encounter this problem.

**Comment by Ahplla** [comment]
Same, Pixel 5

**Comment by Psk-Ita** [comment]
@Urzu7 you can try installing MiXplorer as user app or following instruction on setup to persist DocumentUI and other system app
