### ISSUE TITLE
Breaks DocumentsUIGoogle

### ISSUE THREAD

**Issue by Ahplla** [Magisk-Modules-Alt-Repo/MiXplorer#24]
The problem persists, which is surreal.

How can a repositorynlike this allow the use of the highly regarded name of MiXplorer and ruin it miserably?

Even with interactive installation, the module breaks DocumentsUi. With or without persist it breaks.

Could someone more qualified please assist the Dev of this module or appropriate it?

ROM: Pixel 5, Android 11

![Screenshot_20230426-161638_Firefox_Nightly](https://user-images.githubusercontent.com/16189267/234687494-d025b50c-5b93-49c7-a6b8-cae27fc3e7cc.png)

<details><summary>Crash Log</summary>
<p>

```
Process: com.google.android.documentsui
PID: 12222
UID: 10082
Flags: 0x30c9be45
Package: com.google.android.documentsui v301500700 (r_aml_301500700)
Foreground: Yes
Process-Runtime: 46832
Build: Xiaomi/platina/platina:10/QKQ1.190910.002/V12.0.3.0.QDTMIXM:user/release-keys

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{74b5241 12222:com.google.android.documentsui/u0a82} (pid=12222, uid=10082) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1229)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2627)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2615)
	at com.android.documentsui.roots.ProvidersCache.loadRootsForAuthority(ProvidersCache.java:330)
	at com.android.documentsui.roots.ProvidersCache.access$1400(ProvidersCache.java:81)
	at com.android.documentsui.roots.ProvidersCache$UpdateTask.handleDocumentsProvider(ProvidersCache.java:573)
	at com.android.documentsui.roots.ProvidersCache$UpdateTask.doInBackground(ProvidersCache.java:529)
	at com.android.documentsui.roots.ProvidersCache$UpdateTask.doInBackground(ProvidersCache.java:488)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.content.ContentService.registerContentObserver(ContentService.java:355)
	at android.content.IContentService$Stub.onTransact(IContentService.java:482)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)
```

</p>
</details>

**Comment by Psk-Ita** [comment]
you should read setup instructions, it ask you to persist or not DocumentsUI etc

also give a look to module's readme
<code>if you like the idea of having all featureds ready, you should just flash the zip via magisk.
if you prefer skipping one or more addons you can just open the zip file, navigate to /system/app/ folder, install MiXplorer main apk, plus the add-ons you prefer
or you should go to /data/adb/packages/MiXplorer/system/app/ and simply delete the undesired ones.
</code>

you are completely free to modify the module once downloaded,
you are free to update it your self,
you are free to install provided apps as user apps
 you can do everithing your side, not asking me to update the module

Regards
