### ISSUE TITLE
Stuck on Boot loading

### ISSUE THREAD

**Issue by Ahplla** [Magisk-Modules-Alt-Repo/MiXplorer#8]
### This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

Process: system_server
Build: Xiaomi/platina/platina:10/QKQ1.190910.002/V12.0.3.0.QDTMIXM:user/release-keys

java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.mixplorer (/system/system_ext/priv-app/com.mixplorer): android.permission.WRITE_MEDIA_STORAGE, com.mixplorer (/system/system_ext/priv-app/com.mixplorer): android.permission.PACKAGE_USAGE_STATS}
	at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:4705)
	at com.android.server.pm.permission.PermissionManagerService.access$500(PermissionManagerService.java:178)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:4788)
	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21708)
	at com.android.server.SystemServer.startOtherServices(SystemServer.java:2222)
	at com.android.server.SystemServer.run(SystemServer.java:609)
	at com.android.server.SystemServer.main(SystemServer.java:425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

**Comment by Psk-Ita** [comment]
this should be solved with next updates
I made some mistakes trying to move assets from /app folder to /priv-app
